### PR TITLE
Fix names of params in Chains #614 and spacing issue in fit show #598

### LINKED ISSUE #614: Error when constructing Chain in Bayesian estimation when matrix dimensions are larger than one
```julia
julia> theopp = read_pumas(example_nmtran_data("event_data/THEOPP"),cvs = [:SEX,:WT]);

julia> theopmodel_bayes = @model begin
             @param begin
               θ ~ Constrained(MvNormal([1.9,0.0781,0.0463,1.5,0.4],
                                        Diagonal([9025, 15.25, 5.36, 5625, 400])),
                               lower=[0.1,0.008,0.0004,0.1,0.0001],
                               upper=[5,0.5,0.09,5,1.5],
                               init=[1.9,0.0781,0.0463,1.5,0.4]
                               )
               Ω ~ InverseWishart(2, [0.9 0; 0 0.9] .* (2 + 1 + 1)) # NONMEM specifies the inverse Wishart in terms of its mode
               σ ∈ RealDomain(lower=0.0, init=0.388)
julia> theopmodel_bayes = @model begin
             @param begin
               θ ~ Constrained(MvNormal([1.9,0.0781,0.0463,1.5,0.4],
                                        Diagonal([9025, 15.25, 5.36, 5625, 400])),
                               lower=[0.1,0.008,0.0004,0.1,0.0001],
                               upper=[5,0.5,0.09,5,1.5],
                               init=[1.9,0.0781,0.0463,1.5,0.4]
                               )
               Ω ~ InverseWishart(2, [0.9 0; 0 0.9] .* (2 + 1 + 1)) # NONMEM specifies the inverse Wishart in terms of its mode
               σ ∈ RealDomain(lower=0.0, init=0.388)
             end

             @random begin
               η ~ MvNormal(Ω)
             end

             @pre begin
               Ka = (SEX == 1 ? θ[1] : θ[4]) + η[1]
               K = θ[2]
               CL  = θ[3]*(WT/70)^θ[5] + η[2]
               V = CL/K
               SC = V/(WT/70)
             end

             @covariates SEX WT

             @vars begin
                 conc = Central / SC
             end

             @dynamics OneCompartmentModel

             @derived begin
                 dv ~ @. Normal(conc,sqrt(σ)+eps())
             end
         end;

julia> Pumas.fit(theopmodel_bayes, theopp, Pumas.BayesMCMC(), nsamples=10)
Sampling100%|███████████████████████████████| Time: 0:00:03
  iteration:           10
  acceptance_rate:     1.0
  n_steps:             2048
  hamiltonian_energy:  220.68667892797353
  numerical_error:     false
  is_accept:           true
  precondition:        DiagEuclideanMetric([1.0, 1.0, 1.0, 1.0, 1.0, 1 ...])
  step_size:           0.0005152686727840223
  log_density:         -203.48349216819736
  tree_depth:          11
┌ Info: Finished 10 sampling steps in 3.185283833 (s)
│   h = Hamiltonian(metric=DiagEuclideanMetric([1.0, 1.0, 1.0, 1.0, 1.0, 1 ...]))
│   τ = NUTS{Multinomial}(integrator=Leapfrog(ϵ=0.000515), max_depth=10), Δ_max=1000.0)
│   EBFMI(Hs) = 2.523235175848738
└   mean(αs) = 0.6921050147421806
It's working
ERROR: ArgumentError: the length of each axis must match the corresponding size of data
Stacktrace:
 [1] AxisArrays.AxisArray(::Array{Float64,3}, ::Tuple{AxisArrays.Axis{:iter,StepRange{Int64,Int64}},AxisArrays.Axis{:var,Array{String,1}},AxisArrays.Axis{:chain,Array{Int64,1}}}) at /Users/andreasnoack/.julia/packages/AxisArrays/G6pZY/src/core.jl:222
 [2] AxisArrays.AxisArray(::Array{Float64,3}, ::AxisArrays.Axis{:iter,StepRange{Int64,Int64}}, ::Vararg{Union{Axis, AbstractArray{T,1} where T},N} where N) at /Users/andreasnoack/.julia/packages/AxisArrays/G6pZY/src/core.jl:215
 [3] #Chains#24(::Int64, ::Int64, ::Missing, ::NamedTuple{(),Tuple{}}, ::Type, ::Array{Float64,3}, ::Array{String,1}, ::Dict{Symbol,Array{Any,1}}) at /Users/andreasnoack/.julia/packages/MCMCChains/x3N5v/src/chains.jl:134
 [4] #Chains#19 at ./none:0 [inlined]
 [5] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:start, :thin, :evidence, :info),Tuple{Int64,Int64,Missing,NamedTuple{(),Tuple{}}}}, ::Type{MCMCChains.Chains}, ::Array{Float64,2}, ::Array{String,1}, ::Dict{Symbol,Array{Any,1}}) at ./none:0
 [6] #Chains#9(::Int64, ::Int64, ::Missing, ::NamedTuple{(),Tuple{}}, ::Type, ::Array{Array{Float64,1},1}, ::Array{String,1}, ::Dict{Symbol,Array{Any,1}}) at /Users/andreasnoack/.julia/packages/MCMCChains/x3N5v/src/chains.jl:28
 [7] Type at /Users/andreasnoack/.julia/packages/MCMCChains/x3N5v/src/chains.jl:27 [inlined] (repeats 2 times)
 [8] #fit#540(::Int64, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::PumasModel{ParamSet{NamedTuple{(:θ, :Ω, :σ),Tuple{Constrained{MvNormal{Float64,PDMats.PDiagMat{Float64,Array{Float64,1}},Array{Float64,1}},VectorDomain{Array{Float64,1},Array{Float64,1}}},InverseWishart{Float64,PDMats.PDMat{Float64,Array{Float64,2}}},RealDomain{Float64}}}},getfield(Main, Symbol("##133#138")),getfield(Main, Symbol("##134#139")),getfield(Main, Symbol("##135#140")),OneCompartmentModel,getfield(Main, Symbol("##136#141")),getfield(Main, Symbol("##137#142"))}, ::Array{Subject{NamedTuple{(:dv,),Tuple{Array{Union{Missing, Float64},1}}},NamedTuple{(:SEX, :WT),Tuple{Int64,Float64}},Array{Pumas.Event{Float64,Float64,Float64,Float64,Float64,Float64,Int64},1},Array{Float64,1}},1}, ::Pumas.BayesMCMC, ::NamedTuple{(:θ, :Ω, :σ),Tuple{Array{Float64,1},Array{Float64,2},Float64}}) at /Users/andreasnoack/.julia/dev/Pumas/src/estimation/bayes.jl:161
 [9] #fit at ./none:0 [inlined] (repeats 2 times)
 [10] top-level scope at none:0
```

The problem is https://github.com/PumasAI/Pumas.jl/blob/8356a61bf648206c2de17ca77487fcebeefb0402/src/estimation/bayes.jl#L151-L160 which doesn't take into account that a PD matrix only consists of `n*(n+1)/2` parameters. Instead, the names should be constructed with a dispatch mechanism similar to https://github.com/PumasAI/Pumas.jl/blob/8356a61bf648206c2de17ca77487fcebeefb0402/src/estimation/show.jl#L52-L63. Ideally, they'd use the same functions for constructing the names.

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

File: src/estimation/bayes.jl [hunk 1]
```diff
@@ -149,14 +149,9 @@ function Distributions.fit(model::PumasModel, data::Population, ::BayesMCMC, θ_
...
-  for name in keys(θ_init)
-    if length(getproperty(θ_init, name)) == 1 || typeof(getproperty(θ_init, name)) <: Number
-      push!(names,String(name))
-    else
-      for param_len in 1:length(getproperty(θ_init, name))
-        push!(names, string(name,param_len))
-      end
-    end
+  vals = []
+  for (name,val) in pairs(trans(samples[1]))
```
Comment (andreasnoack) [inline src/estimation/bayes.jl]: Instead of recomputing `trans(samples[1])` you can use a different name for  `trans.(samples)` and just reuse the first element of that array. The performance issue of reusing the same variable for different types doesn't matter much here but it makes a bit easier to reason about the variables if they don't change type.

**Comment by andreasnoack** [comment]
Could you also add a lower bound on `MCMCChains` to make sure the new constructor is available?

**Comment by andreasnoack** [comment]
You'd also have to adjust the display test in `simple_model.jl`. It's the one that is failing.

**Comment by Vaibhavdixit02** [comment]
That's a cool test, I hadn't seen that before!
